language: python
python:
  - "3.6"
install:
  - pip install codecov
  - pip install pytest==3.0.7
  - pip install pytest-cov==2.5.1
script:
  - python -m pytest -v --cov . --cov-report term-missing
after_success:
  - codecov  
notifications:
  email: false